// Code generated by mockery v2.9.5. DO NOT EDIT.

package mocks

import (
	httpserver "github.com/satriowisnugroho/catalog/pkg/httpserver"
	mock "github.com/stretchr/testify/mock"
)

// Option is an autogenerated mock type for the Option type
type Option struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *Option) Execute(_a0 *httpserver.Server) {
	_m.Called(_a0)
}
