// Code generated by mockery v2.9.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	sqlx "github.com/jmoiron/sqlx"
)

// PostgresTransactionRepositoryInterface is an autogenerated mock type for the PostgresTransactionRepositoryInterface type
type PostgresTransactionRepositoryInterface struct {
	mock.Mock
}

// CommitTransactionQuery provides a mock function with given fields: ctx, tx
func (_m *PostgresTransactionRepositoryInterface) CommitTransactionQuery(ctx context.Context, tx *sqlx.Tx) error {
	ret := _m.Called(ctx, tx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx) error); ok {
		r0 = rf(ctx, tx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RollbackTransactionQuery provides a mock function with given fields: ctx, tx
func (_m *PostgresTransactionRepositoryInterface) RollbackTransactionQuery(ctx context.Context, tx *sqlx.Tx) error {
	ret := _m.Called(ctx, tx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx) error); ok {
		r0 = rf(ctx, tx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StartTransactionQuery provides a mock function with given fields: ctx
func (_m *PostgresTransactionRepositoryInterface) StartTransactionQuery(ctx context.Context) (*sqlx.Tx, error) {
	ret := _m.Called(ctx)

	var r0 *sqlx.Tx
	if rf, ok := ret.Get(0).(func(context.Context) *sqlx.Tx); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqlx.Tx)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
