// Code generated by mockery v2.9.5. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/satriowisnugroho/catalog/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// ProductUsecaseInterface is an autogenerated mock type for the ProductUsecaseInterface type
type ProductUsecaseInterface struct {
	mock.Mock
}

// BulkReduceQtyProduct provides a mock function with given fields: ctx, payload
func (_m *ProductUsecaseInterface) BulkReduceQtyProduct(ctx context.Context, payload *entity.BulkReduceQtyProductPayload) ([]*entity.Product, error) {
	ret := _m.Called(ctx, payload)

	var r0 []*entity.Product
	if rf, ok := ret.Get(0).(func(context.Context, *entity.BulkReduceQtyProductPayload) []*entity.Product); ok {
		r0 = rf(ctx, payload)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Product)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *entity.BulkReduceQtyProductPayload) error); ok {
		r1 = rf(ctx, payload)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateProduct provides a mock function with given fields: ctx, payload
func (_m *ProductUsecaseInterface) CreateProduct(ctx context.Context, payload *entity.ProductPayload) (*entity.Product, error) {
	ret := _m.Called(ctx, payload)

	var r0 *entity.Product
	if rf, ok := ret.Get(0).(func(context.Context, *entity.ProductPayload) *entity.Product); ok {
		r0 = rf(ctx, payload)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Product)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *entity.ProductPayload) error); ok {
		r1 = rf(ctx, payload)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProductByID provides a mock function with given fields: ctx, productID
func (_m *ProductUsecaseInterface) GetProductByID(ctx context.Context, productID int) (*entity.Product, error) {
	ret := _m.Called(ctx, productID)

	var r0 *entity.Product
	if rf, ok := ret.Get(0).(func(context.Context, int) *entity.Product); ok {
		r0 = rf(ctx, productID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Product)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, productID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProducts provides a mock function with given fields: ctx, payload
func (_m *ProductUsecaseInterface) GetProducts(ctx context.Context, payload *entity.GetProductPayload) ([]*entity.Product, int, error) {
	ret := _m.Called(ctx, payload)

	var r0 []*entity.Product
	if rf, ok := ret.Get(0).(func(context.Context, *entity.GetProductPayload) []*entity.Product); ok {
		r0 = rf(ctx, payload)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Product)
		}
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(context.Context, *entity.GetProductPayload) int); ok {
		r1 = rf(ctx, payload)
	} else {
		r1 = ret.Get(1).(int)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, *entity.GetProductPayload) error); ok {
		r2 = rf(ctx, payload)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// UpdateProduct provides a mock function with given fields: ctx, productID, payload
func (_m *ProductUsecaseInterface) UpdateProduct(ctx context.Context, productID int, payload *entity.ProductPayload) (*entity.Product, error) {
	ret := _m.Called(ctx, productID, payload)

	var r0 *entity.Product
	if rf, ok := ret.Get(0).(func(context.Context, int, *entity.ProductPayload) *entity.Product); ok {
		r0 = rf(ctx, productID, payload)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Product)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int, *entity.ProductPayload) error); ok {
		r1 = rf(ctx, productID, payload)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
