basePath: /v1
definitions:
  entity.Product:
    properties:
      category:
        type: string
      condition:
        type: integer
      created_at:
        type: string
      id:
        type: integer
      price:
        type: integer
      qty:
        type: integer
      sku:
        type: string
      tenant:
        type: integer
      title:
        type: string
      updated_at:
        type: string
    type: object
  response.ErrorBody:
    properties:
      errors:
        items:
          $ref: '#/definitions/response.ErrorInfo'
        type: array
      meta: {}
    type: object
  response.ErrorInfo:
    properties:
      code:
        type: integer
      field:
        type: string
      message:
        type: string
    type: object
  response.MetaInfo:
    properties:
      http_status:
        type: integer
    type: object
  response.SuccessBody:
    properties:
      data: {}
      message:
        type: string
      meta: {}
    type: object
host: localhost:9999
info:
  contact: {}
  description: An API Documentation
  title: Catalog API
  version: "1.0"
paths:
  /products:
    post:
      consumes:
      - application/json
      description: An API to create product
      operationId: create
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.SuccessBody'
            - properties:
                data:
                  $ref: '#/definitions/entity.Product'
                meta:
                  $ref: '#/definitions/response.MetaInfo'
              type: object
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.ErrorBody'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorBody'
      summary: Create Product
      tags:
      - product
  /products/{id}:
    get:
      consumes:
      - application/json
      description: An API to show product detail
      operationId: detail
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.SuccessBody'
            - properties:
                data:
                  $ref: '#/definitions/entity.Product'
                meta:
                  $ref: '#/definitions/response.MetaInfo'
              type: object
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.ErrorBody'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorBody'
      summary: Show Product Detail
      tags:
      - product
swagger: "2.0"
