basePath: /v1
definitions:
  entity.BulkReduceQtyProductItemPayload:
    properties:
      req_qty:
        type: integer
      sku:
        type: string
    type: object
  entity.BulkReduceQtyProductPayload:
    properties:
      items:
        items:
          $ref: '#/definitions/entity.BulkReduceQtyProductItemPayload'
        type: array
    type: object
  entity.Product:
    properties:
      category:
        type: string
      condition:
        type: integer
      created_at:
        type: string
      id:
        type: integer
      price:
        type: integer
      qty:
        type: integer
      sku:
        type: string
      tenant:
        type: integer
      title:
        type: string
      updated_at:
        type: string
    type: object
  entity.SwaggerProductPayload:
    properties:
      category:
        type: string
      condition:
        type: integer
      price:
        type: integer
      qty:
        type: integer
      tenant:
        type: string
      title:
        type: string
    type: object
  response.ErrorBody:
    properties:
      errors:
        items:
          $ref: '#/definitions/response.ErrorInfo'
        type: array
      meta: {}
    type: object
  response.ErrorInfo:
    properties:
      code:
        type: integer
      field:
        type: string
      message:
        type: string
    type: object
  response.MetaInfo:
    properties:
      http_status:
        type: integer
      limit:
        type: integer
      offset:
        type: integer
      total:
        type: integer
    type: object
  response.SuccessBody:
    properties:
      data: {}
      message:
        type: string
      meta: {}
    type: object
host: localhost:9999
info:
  contact: {}
  description: An API Documentation
  title: Catalog API
  version: "1.0"
paths:
  /products:
    get:
      consumes:
      - application/json
      description: An API to show product list
      operationId: list
      parameters:
      - default: lorem
        description: Tenant Header
        example: lorem, ipsum
        in: header
        name: X-Tenant
        required: true
        type: string
      - description: title search by keyword
        in: query
        name: keyword
        type: string
      - description: sku product
        in: query
        name: sku
        type: string
      - description: category product
        in: query
        name: category
        type: string
      - description: condition product
        in: query
        name: condition
        type: integer
      - description: order by
        in: query
        name: orderby
        type: string
      - description: offset
        in: query
        name: offset
        type: integer
      - description: limit
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.SuccessBody'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/entity.Product'
                  type: array
                meta:
                  $ref: '#/definitions/response.MetaInfo'
              type: object
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.ErrorBody'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorBody'
      summary: Show Product List
      tags:
      - product
    post:
      consumes:
      - application/json
      description: An API to create product
      operationId: create
      parameters:
      - description: Product Payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/entity.SwaggerProductPayload'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.SuccessBody'
            - properties:
                data:
                  $ref: '#/definitions/entity.Product'
                meta:
                  $ref: '#/definitions/response.MetaInfo'
              type: object
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.ErrorBody'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/response.ErrorBody'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorBody'
      summary: Create Product
      tags:
      - product
  /products/{id}:
    get:
      consumes:
      - application/json
      description: An API to show product detail
      operationId: detail
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.SuccessBody'
            - properties:
                data:
                  $ref: '#/definitions/entity.Product'
                meta:
                  $ref: '#/definitions/response.MetaInfo'
              type: object
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.ErrorBody'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorBody'
      summary: Show Product Detail
      tags:
      - product
    put:
      consumes:
      - application/json
      description: An API to update product
      operationId: update
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      - description: Product Payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/entity.SwaggerProductPayload'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.SuccessBody'
            - properties:
                data:
                  $ref: '#/definitions/entity.Product'
                meta:
                  $ref: '#/definitions/response.MetaInfo'
              type: object
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.ErrorBody'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/response.ErrorBody'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorBody'
      summary: Update Product
      tags:
      - product
  /products/bulk-reduce-qty:
    post:
      consumes:
      - application/json
      description: An API to bulk reduce quantity product
      operationId: bulk-reduce-qty
      parameters:
      - default: lorem
        description: Tenant Header
        example: lorem, ipsum
        in: header
        name: X-Tenant
        required: true
        type: string
      - description: Payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/entity.BulkReduceQtyProductPayload'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.SuccessBody'
            - properties:
                data:
                  $ref: '#/definitions/entity.Product'
                meta:
                  $ref: '#/definitions/response.MetaInfo'
              type: object
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.ErrorBody'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/response.ErrorBody'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorBody'
      summary: Bulk Reduce Quantity Product
      tags:
      - product
swagger: "2.0"
